features:
  node_user_picture: 1
  comment_user_picture: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
zurb_foundation_status_in_reveal: 0
zurb_foundation_use_respondjs: 0
zurb_foundation_meta_header_grid: 0
zurb_foundation_top_bar_enable: '0'
zurb_foundation_top_bar_grid: 0
zurb_foundation_top_bar_sticky: 0
zurb_foundation_top_bar_scrolltop: 0
zurb_foundation_top_bar_is_hover: 1
zurb_foundation_top_bar_menu_text: ''
zurb_foundation_top_bar_custom_back_text: 0
zurb_foundation_top_bar_back_text: ''
zurb_foundation_top_bar_mobile_show_parent_link: 0
zurb_foundation_top_bar_search: 0
zurb_foundation_page_site_name: 0
zurb_foundation_page_site_logo: 0
zurb_foundation_page_account_info: 1
zurb_foundation_disable_base_css: 0
zurb_foundation_disable_base_js: 0
enable_copyright_footer: 0
enable_ebi_footer: 0
enable_header_bar: 1
header_background_color: '#967455'
header_type: image
header_background_images:
  - '19'
